### ISSUE TITLE
Incorrect escape.

### ISSUE THREAD

**Issue by themihai** [annevk/webvtt#11]
Why characters such ampersand (`&`) can be html-encoded(`&amp;`) and other characters such `'` encoded as `&#39;` are not allowed? Trying to validate  the track below throws the error: `Line 8, column 31: Incorrect escape.`

    WEBVTT
    
    00:11.000 --> 00:13.000 vertical:rl
    <v Roger Bingham>Tom &amp; Jerry
    
    00:13.000 --> 00:16.000
    <v Roger Bingham>See you at 5&#39;34

**Comment by annevk** [comment]
I think that's because WebVTT changed and nobody bothered to update this. @zcorpan?

**Comment by zcorpan** [comment]
Yeah. But I think WebVTT implementations should change this because content uses HTML escapes and expects it to work. Users are exposed to things like `&quot;` instead of `"`. But a validator right now should probably warn against using them until it is widely supported.
