### ISSUE TITLE
Timestamps with one digit allowed

### ISSUE THREAD

**Issue by swegen** [annevk/webvtt#17]
The [spec](https://www.w3.org/TR/webvtt1/#webvtt-timestamp) requires that a WebVTT timestamp has two or more ASCII digits for hours (if non-zero) and two ASCII digits for minutes.

```
WEBVTT

1:23.456 --> 1:23:45.678
```

However, the validator accepts above input as valid. The first value length in a timestamp before the first colon is not checked.

**Comment by swegen** [comment]
I tested this with Firefox and it parses a timestamp with one digit hour just fine, but it completely skips a cue using short timestamp with one digit minute.

**Comment by annevk** [comment]
Yeah, that's correct. Minutes have to be exactly two digits. (The specification also describes parser requirements. My implementation has a parser implementation per the specification and intertwined with that a validator.)

**Comment by swegen** [comment]
But still, your parser accepts the one digit minutes like below, for example.

```
WEBVTT

0:00.000 --> 1:00.000
```

**Comment by yclicc** [comment]
The hours (if present) also have to be at least two digits, but the validator currently doesn't check that. It marked my VTT as OK but then when I loaded it into AblePlayer (which recommends using your validator) it didn't load any captions past the hour mark.

**Comment by annevk** [comment]
File a new issue on that?
